import { expect, test } from '@playwright/test'

test('treatments reuse reviews immediately below the hero and retain fallback', async ({ page }) => {
  await page.route('**/api/google-reviews', route => route.fulfill({ json: { status: 'unavailable' } }))
  await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
  await expect(page.locator('.treatment-hero + .google-reviews')).toHaveCount(1)
  await expect(page.locator('.google-reviews').getByRole('link', { name: 'Read reviews on Google' })).toBeVisible()
  await expect(page.locator('.treatment-gallery-item')).toHaveCount(3)
  await expect(page.locator('.results .disclaimer')).toContainText('Layout previews only')
})

test('gallery opens a modal, closes with Escape, and restores keyboard focus', async ({ page }) => {
  await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: 'Show photo 3: The people behind your care' }).click()
  const thumbnail = page.getByRole('button', { name: 'Enlarge: The people behind your care' })
  await thumbnail.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('img')).toHaveAttribute('alt', 'The team at Alrata Art of Dentistry')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(thumbnail).toBeFocused()
})

test('multiple comparisons wrap and the shared slider supports keyboard input', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
  const comparisons = page.getByRole('region', { name: 'Treatment before and after comparisons' })
  await comparisons.scrollIntoViewIfNeeded()
  await comparisons.getByRole('slider').press('End')
  await expect(comparisons.getByRole('slider')).toHaveValue('100')
  await comparisons.getByRole('button', { name: 'Next comparison' }).click()
  await expect(comparisons.getByRole('slider')).toHaveAttribute('aria-label', /Comparison preview 02/)
  await expect(comparisons.getByRole('slider')).toHaveValue('50')
  await comparisons.getByRole('button', { name: 'Show comparison preview 03' }).click()
  await comparisons.getByRole('button', { name: 'Next comparison' }).click()
  await expect(comparisons.getByRole('button', { name: 'Show comparison preview 01' })).toHaveAttribute('aria-current', 'true')
  await expect(page.locator('.comparison-caption')).toContainText('not a patient result')
})

for (const width of [390, 768, 1440]) {
  test(`media sections fit at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
    for (const selector of ['.treatment-gallery', '.treatment-comparisons']) {
      await page.locator(selector).scrollIntoViewIfNeeded()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    }
    for (const thumbnail of await page.locator('.gallery-thumbnail img').all()) {
      await expect.poll(() => thumbnail.evaluate(node => (node as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
    }
    await page.locator('.treatment-gallery-item[data-position="center"] button').click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    const bounds = await dialog.boundingBox()
    expect(bounds!.width).toBeLessThanOrEqual(width)
    await dialog.getByRole('button', { name: 'Close gallery' }).click()
    await expect(dialog).not.toBeVisible()
  })
}

test('gallery thumbnails, side cards, keyboard and rapid navigation stay synchronized', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
  const gallery = page.getByRole('region', { name: 'Crowns photo gallery' })
  await gallery.getByRole('button', { name: 'Show photo 3: The people behind your care' }).click()
  await expect(gallery.locator('.gallery-count')).toHaveText('03 / 03')
  await gallery.press('ArrowRight')
  await expect(gallery.locator('.gallery-thumbnail[aria-current="true"]')).toHaveAttribute('aria-label', /Show photo 1/)
  const side = gallery.locator('[data-position="right"] button')
  await side.scrollIntoViewIfNeeded()
  const bounds = await side.boundingBox()
  const sidePoint = { x: Math.min(bounds!.x + bounds!.width - 30, page.viewportSize()!.width - 20), y: bounds!.y + bounds!.height / 2 }
  expect(await page.evaluate(({ x, y }) => document.elementFromPoint(x, y)?.closest('button')?.getAttribute('aria-label'), sidePoint)).toBe('Show: A conversation about your care')
  await page.mouse.click(sidePoint.x, sidePoint.y)
  await expect(gallery.locator('.gallery-count')).toHaveText('02 / 03')
  await gallery.press('End')
  await gallery.press('Home')
  for (let i = 0; i < 7; i++) await gallery.press('ArrowRight')
  await expect(gallery.locator('.gallery-count')).toHaveText('02 / 03')
  await expect(gallery.getByRole('button', { name: /automatic gallery rotation/ })).toHaveCount(0)
})

test('view more offers the full grid, an uncropped viewer, focus restoration and backdrop dismissal', async ({ page }) => {
  await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
  const more = page.getByRole('button', { name: /View more/ })
  await more.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.locator('.gallery-grid-photo')).toHaveCount(3)
  await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
  await dialog.getByRole('button', { name: 'Enlarge: The people behind your care' }).click()
  await expect(dialog.getByRole('button', { name: 'Back to gallery' })).toBeFocused()
  await expect(dialog.locator('.gallery-dialog-image img')).toHaveCSS('object-fit', 'contain')
  await dialog.getByRole('button', { name: 'Next enlarged image' }).click()
  await expect(dialog.locator('.gallery-count')).toHaveText('1 / 3')
  await page.keyboard.press('ArrowLeft')
  await expect(dialog.locator('.gallery-count')).toHaveText('3 / 3')
  await dialog.getByRole('button', { name: 'Back to gallery' }).click()
  await expect(dialog.getByRole('button', { name: 'Enlarge: The people behind your care' })).toBeFocused()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  expect(await page.evaluate(() => !!document.activeElement?.closest('dialog'))).toBeTruthy()
  await page.keyboard.press('Escape')
  await expect(more).toBeFocused()
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  await more.click()
  await page.mouse.click(1, 1)
  await expect(dialog).not.toBeVisible()
})

test('gallery autoplay pauses for hover, focus, modal, manual input and reduced motion', async ({ page }) => {
  await page.clock.install()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
  const gallery = page.locator('.treatment-carousel')
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('01 / 03')
  await gallery.scrollIntoViewIfNeeded()
  await page.mouse.move(1, 1)
  await expect(gallery.getByRole('button', { name: 'Pause automatic gallery rotation' })).toBeVisible()
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('02 / 03')
  await gallery.hover()
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('02 / 03')
  await gallery.focus()
  await page.mouse.move(1, 1)
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('02 / 03')
  await page.getByRole('button', { name: /View more/ }).click()
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('02 / 03')
  await page.keyboard.press('Escape')
  await gallery.getByRole('button', { name: 'Next gallery image' }).click()
  await expect(gallery.getByRole('button', { name: 'Start automatic gallery rotation' })).toBeVisible()
  await gallery.evaluate(node => (node as HTMLElement).blur())
  await page.locator('#gallery-title').click()
  await page.mouse.move(1, 1)
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('03 / 03')
  await gallery.getByRole('button', { name: 'Start automatic gallery rotation' }).click()
  await page.locator('#gallery-title').click()
  await page.mouse.move(1, 1)
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('01 / 03')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.clock.runFor(6500)
  await expect(gallery.locator('.gallery-count')).toHaveText('01 / 03')
})

test('horizontal drag navigates without opening the viewer and vertical gestures are preserved', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/crowns', { waitUntil: 'domcontentloaded' })
  const stage = page.locator('.treatment-gallery-stage')
  // Establish hydration and settled font metrics before using pointer coordinates.
  await page.locator('.treatment-carousel').press('End')
  await expect(page.locator('.gallery-caption-row .gallery-count')).toHaveText('03 / 03')
  await page.locator('.treatment-carousel').press('Home')
  await expect(page.locator('.gallery-caption-row .gallery-count')).toHaveText('01 / 03')
  await page.evaluate(() => document.fonts.ready)
  await stage.scrollIntoViewIfNeeded()
  const box = await stage.boundingBox()
  const x = box!.x + box!.width * .7
  const y = box!.y + box!.height / 2
  await page.mouse.move(x, y)
  await page.mouse.down()
  await page.mouse.move(x - 100, y, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('.gallery-caption-row .gallery-count')).toHaveText('02 / 03')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(stage).toHaveCSS('touch-action', 'pan-y pinch-zoom')
  await page.mouse.move(x, y)
  await page.mouse.down()
  await page.mouse.move(x, y + 80, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('.gallery-caption-row .gallery-count')).toHaveText('02 / 03')
})
